/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package marvelsgroup;

import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author hp-pc
 */
public class FinalBill extends javax.swing.JFrame {

    ArrayList<BillMedsClass> arr;
    float total,nettotal;
    public FinalBill() {
        initComponents();
    }
    public FinalBill(ArrayList arra, float total)
    {
        initComponents();
        arr=new ArrayList<BillMedsClass>(arra);
        this.total=total;
        totalBox.setText(this.total+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnameBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addressBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        docNameBox = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        totalBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        discountBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        netTotalBox = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        cancelButtin = new javax.swing.JButton();
        CSDButton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BILLING");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Patient Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Doctor's Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Total");

        totalBox.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Discount %");

        discountBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                discountBoxMouseMoved(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Net Total");

        netTotalBox.setEditable(false);

        applyButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        applyButton.setText("Apply Discount");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        finishButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finishButton.setText("Finish!");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        cancelButtin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButtin.setForeground(java.awt.Color.red);
        cancelButtin.setText("Cancel Bill");
        cancelButtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtinActionPerformed(evt);
            }
        });

        CSDButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CSDButton.setText("Help");
        CSDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSDButtonActionPerformed(evt);
            }
        });

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(finishButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42)
                                .addComponent(cancelButtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(362, 362, 362))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netTotalBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(discountBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(CSDButton, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addGap(88, 88, 88))))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(docNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(pnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {discountBox, netTotalBox, totalBox});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addressBox, docNameBox, pnameBox});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(pnameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(addressBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(docNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalBox, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(discountBox)
                            .addComponent(jLabel6)
                            .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CSDButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(netTotalBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButtin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backbutton))
                .addGap(53, 53, 53))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {backbutton, cancelButtin});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        float pc=Float.parseFloat(discountBox.getText());
        nettotal=(total-((pc/100)*total));
        netTotalBox.setText(nettotal+"");
    }//GEN-LAST:event_applyButtonActionPerformed

    private void discountBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_discountBoxMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_discountBoxMouseMoved

    private void cancelButtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtinActionPerformed
        BillClass bc=new BillClass();
        bc.setVisible(true);
        dispose();
    }//GEN-LAST:event_cancelButtinActionPerformed

    private void CSDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSDButtonActionPerformed
        JOptionPane.showMessageDialog(this, "5% for general public\n11% for senior citizen\n7% for government employees");
    }//GEN-LAST:event_CSDButtonActionPerformed

    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        int ID=createbill();
        if(ID!=-1)
        {
            createbillmeds(ID);
            updateInventory();
            JOptionPane.showMessageDialog(this, "Bill Successfully Created!");
            FinalBillElement f=new FinalBillElement();
            f.medicine_list=(ArrayList<BillMedsClass>)arr.clone();
            f.addr=addressBox.getText();
            f.dis=Float.parseFloat(discountBox.getText());
            f.dname=docNameBox.getText();
            f.ntotal=Float.parseFloat(netTotalBox.getText());
            f.pname=pnameBox.getText();
            f.total=Float.parseFloat(totalBox.getText());
            f.billID=ID;
            BillClass bc=new BillClass();
            bc.setVisible(true);
            DisplayBill db=new DisplayBill(f);
            db.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Database Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_finishButtonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        BillClass bc=new BillClass(arr, total);
        bc.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void updateInventory()
    {
        int pqty=0;
        Connection conn=MySQLConnect.ConnectDB();
        PreparedStatement pst=null, pst2=null;
        String st="update medicines set qty=? where medname=?";
        String st2="select qty from medicines where medname=?";
        ResultSet rs=null;
        try
        {
            for(int i=0; i<arr.size(); i++)
            {
                pst2=conn.prepareStatement(st2);
                pst2.setString(1, arr.get(i).medname.toLowerCase());
                rs=pst2.executeQuery();
                if(!rs.first())
                {
                    JOptionPane.showMessageDialog(this, "Error");
                }
                else
                {
                    pqty=rs.getInt("qty");
                }
                
                pqty=pqty-arr.get(i).qty;
                pst=conn.prepareStatement(st);
                pst.setInt(1, pqty);
                pst.setString(2, arr.get(i).medname.toLowerCase());
                pst.execute();
                pst.close();    
            }
            conn.close();
            pst.close();
        }
        catch(SQLException e)
        {
            //JOptionPane.showMessageDialog(this, "Error creating billmeds!");
            e.printStackTrace();
        }
    }
    
    private void createbillmeds(int BID)
    {
        Connection conn=MySQLConnect.ConnectDB();
        PreparedStatement pst=null;
        String st="insert into billmed(BID, medname, qty, rate, exdate, bno, amt) values (?,?,?,?,?,?,?)";
        try
        {
            for(int i=0; i<arr.size(); i++)
            {
                pst=conn.prepareStatement(st);
                pst.setInt(1, BID);
                pst.setString(2, arr.get(i).medname);
                pst.setInt(3, arr.get(i).qty);
                pst.setFloat(4, arr.get(i).rate);
                pst.setString(5, arr.get(i).exdate);
                pst.setString(6, arr.get(i).bno);
                pst.setFloat(7, arr.get(i).amt);
                pst.execute();
                pst.close();    
            }
            conn.close();
            pst.close();
        }
        catch(SQLException e)
        {
            //JOptionPane.showMessageDialog(this, "Error creating billmeds!");
            e.printStackTrace();
        }
        
    }
            
    
    
    private int createbill()
    {
        Connection conn=MySQLConnect.ConnectDB();
        PreparedStatement pst=null, pst2=null;
        String st="insert into bills(pname, addr, dname, total, dis, net) values (?,?,?,?,?,?)";
        try
        {
            pst=conn.prepareStatement(st);
            pst.setString(1, pnameBox.getText());
            pst.setString(2, addressBox.getText());
            pst.setString(3, docNameBox.getText());
            pst.setFloat(4, total);
            pst.setFloat(5, Float.parseFloat(discountBox.getText()));
            pst.setFloat(6, Float.parseFloat(netTotalBox.getText()));
            pst.execute();
            //pst.close();
            String st2="select BID from bills where pname=? and addr=? and total=?";
            pst2=conn.prepareStatement(st2);
            pst2.setString(1, pnameBox.getText());
            pst2.setString(2, addressBox.getText());
            pst2.setFloat(3, total);
            ResultSet rs=null;
            rs=pst2.executeQuery();
            rs.first();
            //conn.close();
            //pst2.close();
            int currentID=rs.getInt("BID");
            System.out.println("BID = "+currentID);
            //rs.close();
            
            return currentID;
        }
        catch(SQLException e)
        {
            //JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
        return -1;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CSDButton;
    private javax.swing.JTextField addressBox;
    private javax.swing.JButton applyButton;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton cancelButtin;
    private javax.swing.JTextField discountBox;
    private javax.swing.JTextField docNameBox;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField netTotalBox;
    private javax.swing.JTextField pnameBox;
    private javax.swing.JTextField totalBox;
    // End of variables declaration//GEN-END:variables
}
